### ISSUE TITLE
XQEMU displays no graphical output.

### ISSUE THREAD

**Issue by Xeddius** [espes/xqemu#107]
Qemu starts and displays the text "Guest has not initialized the display (yet)." And does nothing else.

**Comment by JayFoxRox** [comment]
Depending on which version of XQEMU you use, the upstream has moved to https://github.com/xqemu/xqemu/

The message implies a broken MCPX or Flash. Or a bad command line.

**Comment by Xeddius** [comment]
My bios file didn't completely transfer from my Xbox (FTP cut-out partly.) I've since done a re-dump and it now starts and then says the Xbox needs service. :) I've yet to get games launching/working.

**Comment by JayFoxRox** [comment]
[The error number in the upper left corner would be relevant](http://xboxdevwiki.net/Fatal_Error).
Make sure your kernel supports Xbox hardware revision 1.0.

If you don't have a valid HDD, then it might be an error that the dashboard wasn't found.

This might also happen if the DVD content isn't detected (so it would launch to the dashboard to report errors).
[Repack your iso with extract-xiso](https://github.com/XboxDev/extract-xiso).

Also, make sure the kernel (part of the flash / bios image) is patched so it doesn't do security checks. XQEMU does not emulate drive security so copy-protection will always trigger (would always launch dashboard).

I don't think there's much to add here.

---

Again: The new upstream is elsewhere (https://github.com/xqemu/xqemu/) + GitHub is reserved for development discussions.

If you need user support: we are currently in the process of setting up a new discord. See http://xqemu.org/ for more information.

Closed.
