### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by minuteworld** [espes/xqemu#69]
I'm sorry for asking this in the issues tab but as far as I'm aware, this is the only place I can get in touch with  the devs. what makes me believe that this project is dead is when I look at the progress, it was doing great in 2013 but it kinda stopped in the beginning of this year.

I mean, I could see why projects like play! is struggling because it has 2 people actively working on it but this has had 300+ contributors over the years, I know the xbox is hard to emulate but man.

the last video I've seen of this emulator was that everything was rendering fine but it was slow as hell and I don't even know about how the chihiro side is going. I'm not trying to rush anybody, I just wanna know what's going on. like play!, you guys don't have a forum or maybe you do and I'm just dense. you may be hanging out at r/emulation but I'm not using reddit ever again.

care to explain what is going on with the project?

**Comment by espes** [comment]
XQEMU is a fork of QEMU. The Xbox emulation has only ever had 2 significant contributors, myself included: https://github.com/espes/xqemu/commits/xbox/hw/xbox

I've been working on more important things lately. Patches welcome.

**Comment by minuteworld** [comment]
thanks for replying. I respect your dedication.
